const fs = require('fs');
const swaggerAutogen = require('swagger-autogen')();

// Basic API metadata for the generated docs.
//
// NOTE: the schemas live under '@definitions' on purpose. swagger-autogen
// runs every entry of 'definitions' through a type-inference pass that
// rewrites proper JSON Schema into sample-data form. Anything registered under
// '@definitions' is merged in after that pass and is left untouched.
const doc = {
    info: {
        title: 'Plant Care API',
        description:
            'REST API to create, read, update and delete houseplants and their care logs, stored in MongoDB.',
        version: '1.0.0',
    },
    host: 'plant-care-api-bk00.onrender.com',
    basePath: '/',
    schemes: ['https'],
    tags: [
        {
            name: 'Home',
            description: 'Base route of the Plant Care API',
        },
        {
            name: 'Plants',
            description: 'CRUD operations on the plants collection',
        },
        {
            name: 'Care Logs',
            description: 'CRUD operations on the careLogs collection',
        },
    ],
    '@definitions': {
        PlantInput: {
            description:
                'The nine fields required to create or replace a plant. The _id is generated by MongoDB and must not be sent.',
            type: 'object',
            required: [
                'name',
                'species',
                'category',
                'nickname',
                'location',
                'lightRequirement',
                'wateringIntervalDays',
                'acquiredDate',
                'notes',
            ],
            properties: {
                name: { type: 'string', example: 'Monstera' },
                species: { type: 'string', example: 'Monstera deliciosa' },
                category: {
                    type: 'string',
                    enum: ['Succulent', 'Tropical', 'Fern', 'Orchid', 'Cactus', 'Palm', 'Herb', 'Other'],
                    example: 'Tropical',
                },
                nickname: { type: 'string', example: 'Delilah' },
                location: { type: 'string', example: 'Living room window' },
                lightRequirement: {
                    type: 'string',
                    enum: ['Low Light', 'Medium Light', 'Bright Indirect', 'Direct Sun'],
                    example: 'Bright Indirect',
                },
                wateringIntervalDays: { type: 'integer', example: 7 },
                acquiredDate: {
                    type: 'string',
                    description: 'Past date in YYYY-MM-DD format.',
                    example: '2024-03-15',
                },
                notes: { type: 'string', example: 'Leaves started splitting after moving it closer to the window.' },
            },
        },
        Plant: {
            description: 'A stored plant, including the _id that MongoDB assigned on insert.',
            type: 'object',
            required: [
                'name',
                'species',
                'category',
                'nickname',
                'location',
                'lightRequirement',
                'wateringIntervalDays',
                'acquiredDate',
                'notes',
            ],
            properties: {
                _id: {
                    type: 'string',
                    description: 'Assigned by MongoDB when the plant is created. Not sent by the client.',
                    example: '6ab6bd0406634384d69bc582',
                },
                name: { type: 'string', example: 'Monstera' },
                species: { type: 'string', example: 'Monstera deliciosa' },
                category: {
                    type: 'string',
                    enum: ['Succulent', 'Tropical', 'Fern', 'Orchid', 'Cactus', 'Palm', 'Herb', 'Other'],
                    example: 'Tropical',
                },
                nickname: { type: 'string', example: 'Delilah' },
                location: { type: 'string', example: 'Living room window' },
                lightRequirement: {
                    type: 'string',
                    enum: ['Low Light', 'Medium Light', 'Bright Indirect', 'Direct Sun'],
                    example: 'Bright Indirect',
                },
                wateringIntervalDays: { type: 'integer', example: 7 },
                acquiredDate: { type: 'string', example: '2024-03-15' },
                notes: { type: 'string', example: 'Leaves started splitting after moving it closer to the window.' },
            },
        },
        PlantList: {
            description: 'A list of stored plants.',
            type: 'array',
            items: { $ref: '#/definitions/Plant' },
        },
        CareLogInput: {
            description:
                'The five fields required to create or replace a care log. plantId must reference an existing plant.',
            type: 'object',
            required: ['plantId', 'taskType', 'performedDate', 'durationMinutes', 'notes'],
            properties: {
                plantId: {
                    type: 'string',
                    description: 'ObjectId of the plant this log belongs to.',
                    example: '6ab6bd0406634384d69bc582',
                },
                taskType: {
                    type: 'string',
                    enum: ['Watering', 'Fertilizing', 'Repotting', 'Pruning', 'Pest Treatment', 'Repositioning'],
                    example: 'Watering',
                },
                performedDate: {
                    type: 'string',
                    description: 'Past date in YYYY-MM-DD format.',
                    example: '2024-06-01',
                },
                durationMinutes: { type: 'integer', example: 12 },
                notes: { type: 'string', example: 'Top watered until drainage came out.' },
            },
        },
        CareLog: {
            description: 'A stored care log, including the _id that MongoDB assigned on insert.',
            type: 'object',
            required: ['plantId', 'taskType', 'performedDate', 'durationMinutes', 'notes'],
            properties: {
                _id: {
                    type: 'string',
                    description: 'Assigned by MongoDB when the care log is created. Not sent by the client.',
                    example: '6ab6bd0506634384d69bc583',
                },
                plantId: { type: 'string', example: '6ab6bd0406634384d69bc582' },
                taskType: {
                    type: 'string',
                    enum: ['Watering', 'Fertilizing', 'Repotting', 'Pruning', 'Pest Treatment', 'Repositioning'],
                    example: 'Watering',
                },
                performedDate: { type: 'string', example: '2024-06-01' },
                durationMinutes: { type: 'integer', example: 12 },
                notes: { type: 'string', example: 'Top watered until drainage came out.' },
            },
        },
        CareLogList: {
            description: 'A list of stored care logs.',
            type: 'array',
            items: { $ref: '#/definitions/CareLog' },
        },
        IdResponse: {
            description: 'The _id of a newly created document, assigned by MongoDB.',
            type: 'object',
            properties: {
                _id: { type: 'string', example: '6ab6bd0406634384d69bc582' },
            },
        },
        MessageResponse: {
            description: 'Confirmation that the requested change was applied.',
            type: 'object',
            properties: {
                message: { type: 'string', example: 'Plant updated successfully.' },
            },
        },
        ValidationError: {
            description: 'Returned when the request body fails validation.',
            type: 'object',
            properties: {
                error: { type: 'string', example: 'Validation failed.' },
                details: {
                    type: 'array',
                    items: { type: 'string' },
                    example: ['category is required.', 'wateringIntervalDays must be a whole number between 1 and 365.'],
                },
            },
        },
        NotFoundError: {
            description: 'Returned when no document matches the requested id.',
            type: 'object',
            properties: {
                error: { type: 'string', example: 'No plant found with id 6ab6bd0406634384d69bc582.' },
            },
        },
    },
};

// Generate swagger.json from the routes.
// Only index.js is listed because swagger-autogen follows the require() calls
// from there, which is what applies the /plants and /careLogs prefixes.
const outputFile = './swagger.json';
const endpointsFiles = ['./routes/index.js'];

swaggerAutogen(outputFile, endpointsFiles, doc).then(({ data }) => {
    // swagger-autogen keeps the trailing slash of a router's mount path, which
    // makes the docs advertise "/plants/" while the route also answers "/plants".
    let changed = false;
    for (const path of Object.keys(data.paths)) {
        if (path.length > 1 && path.endsWith('/')) {
            const clean = path.replace(/\/+$/, '');
            data.paths[clean] = data.paths[path];
            delete data.paths[path];
            changed = true;
        }
    }
    if (changed) {
        fs.writeFileSync(outputFile, `${JSON.stringify(data, null, 4)}\n`);
    }
});
